/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace MedicineTracker {
  export type BatchStruct = {
    batchId: string;
    productName: string;
    manufacturer: AddressLike;
    manufacturerLabel: string;
    currentStatus: BigNumberish;
    createdAt: BigNumberish;
    units: BigNumberish;
    serial: string;
    originLabel: string;
    destinationLabel: string;
    exists: boolean;
  };

  export type BatchStructOutput = [
    batchId: string,
    productName: string,
    manufacturer: string,
    manufacturerLabel: string,
    currentStatus: bigint,
    createdAt: bigint,
    units: bigint,
    serial: string,
    originLabel: string,
    destinationLabel: string,
    exists: boolean
  ] & {
    batchId: string;
    productName: string;
    manufacturer: string;
    manufacturerLabel: string;
    currentStatus: bigint;
    createdAt: bigint;
    units: bigint;
    serial: string;
    originLabel: string;
    destinationLabel: string;
    exists: boolean;
  };

  export type TelemetryStruct = {
    timestamp: BigNumberish;
    latE6: BigNumberish;
    lngE6: BigNumberish;
    temperatureCp: BigNumberish;
    signer: AddressLike;
    breached: boolean;
  };

  export type TelemetryStructOutput = [
    timestamp: bigint,
    latE6: bigint,
    lngE6: bigint,
    temperatureCp: bigint,
    signer: string,
    breached: boolean
  ] & {
    timestamp: bigint;
    latE6: bigint;
    lngE6: bigint;
    temperatureCp: bigint;
    signer: string;
    breached: boolean;
  };
}

export interface MedicineTrackerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "CARRIER_ROLE"
      | "DEFAULT_ADMIN_ROLE"
      | "INSPECTOR_ROLE"
      | "MANUFACTURER_ROLE"
      | "MAX_TEMP"
      | "MIN_TEMP"
      | "batchTelemetry"
      | "batches"
      | "getBatch"
      | "getRoleAdmin"
      | "getTelemetry"
      | "getTelemetryCount"
      | "grantRole"
      | "hasRole"
      | "logTelemetry"
      | "provisionBatch"
      | "recordVerificationHash"
      | "registerCarrier"
      | "registerInspector"
      | "registerManufacturer"
      | "renounceRole"
      | "revokeBatch"
      | "revokeRole"
      | "supportsInterface"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "BatchProvisioned"
      | "BatchRevoked"
      | "BatchSpoiled"
      | "BatchStatusChanged"
      | "RoleAdminChanged"
      | "RoleGranted"
      | "RoleRevoked"
      | "TelemetryLogged"
      | "VerificationRecorded"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "CARRIER_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "INSPECTOR_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MANUFACTURER_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "MAX_TEMP", values?: undefined): string;
  encodeFunctionData(functionFragment: "MIN_TEMP", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "batchTelemetry",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "batches", values: [string]): string;
  encodeFunctionData(functionFragment: "getBatch", values: [string]): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getTelemetry",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTelemetryCount",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "logTelemetry",
    values: [string, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "provisionBatch",
    values: [string, string, string, BigNumberish, string, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "recordVerificationHash",
    values: [string, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "registerCarrier",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "registerInspector",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "registerManufacturer",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeBatch",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "CARRIER_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "INSPECTOR_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MANUFACTURER_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "MAX_TEMP", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "MIN_TEMP", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "batchTelemetry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "batches", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getBatch", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTelemetry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTelemetryCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "logTelemetry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "provisionBatch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recordVerificationHash",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerCarrier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerInspector",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerManufacturer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeBatch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
}

export namespace BatchProvisionedEvent {
  export type InputTuple = [batchId: string, manufacturer: AddressLike];
  export type OutputTuple = [batchId: string, manufacturer: string];
  export interface OutputObject {
    batchId: string;
    manufacturer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BatchRevokedEvent {
  export type InputTuple = [
    batchId: string,
    admin: AddressLike,
    reason: string
  ];
  export type OutputTuple = [batchId: string, admin: string, reason: string];
  export interface OutputObject {
    batchId: string;
    admin: string;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BatchSpoiledEvent {
  export type InputTuple = [
    batchId: string,
    carrier: AddressLike,
    temperatureCp: BigNumberish
  ];
  export type OutputTuple = [
    batchId: string,
    carrier: string,
    temperatureCp: bigint
  ];
  export interface OutputObject {
    batchId: string;
    carrier: string;
    temperatureCp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BatchStatusChangedEvent {
  export type InputTuple = [batchId: string, newStatus: BigNumberish];
  export type OutputTuple = [batchId: string, newStatus: bigint];
  export interface OutputObject {
    batchId: string;
    newStatus: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleAdminChangedEvent {
  export type InputTuple = [
    role: BytesLike,
    previousAdminRole: BytesLike,
    newAdminRole: BytesLike
  ];
  export type OutputTuple = [
    role: string,
    previousAdminRole: string,
    newAdminRole: string
  ];
  export interface OutputObject {
    role: string;
    previousAdminRole: string;
    newAdminRole: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleGrantedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleRevokedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TelemetryLoggedEvent {
  export type InputTuple = [
    batchId: string,
    carrier: AddressLike,
    temperatureCp: BigNumberish,
    breached: boolean
  ];
  export type OutputTuple = [
    batchId: string,
    carrier: string,
    temperatureCp: bigint,
    breached: boolean
  ];
  export interface OutputObject {
    batchId: string;
    carrier: string;
    temperatureCp: bigint;
    breached: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VerificationRecordedEvent {
  export type InputTuple = [
    batchId: string,
    inspector: AddressLike,
    payloadHash: BytesLike
  ];
  export type OutputTuple = [
    batchId: string,
    inspector: string,
    payloadHash: string
  ];
  export interface OutputObject {
    batchId: string;
    inspector: string;
    payloadHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface MedicineTracker extends BaseContract {
  connect(runner?: ContractRunner | null): MedicineTracker;
  waitForDeployment(): Promise<this>;

  interface: MedicineTrackerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  CARRIER_ROLE: TypedContractMethod<[], [string], "view">;

  DEFAULT_ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  INSPECTOR_ROLE: TypedContractMethod<[], [string], "view">;

  MANUFACTURER_ROLE: TypedContractMethod<[], [string], "view">;

  MAX_TEMP: TypedContractMethod<[], [bigint], "view">;

  MIN_TEMP: TypedContractMethod<[], [bigint], "view">;

  batchTelemetry: TypedContractMethod<
    [arg0: string, arg1: BigNumberish],
    [
      [bigint, bigint, bigint, bigint, string, boolean] & {
        timestamp: bigint;
        latE6: bigint;
        lngE6: bigint;
        temperatureCp: bigint;
        signer: string;
        breached: boolean;
      }
    ],
    "view"
  >;

  batches: TypedContractMethod<
    [arg0: string],
    [
      [
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        string,
        string,
        string,
        boolean
      ] & {
        batchId: string;
        productName: string;
        manufacturer: string;
        manufacturerLabel: string;
        currentStatus: bigint;
        createdAt: bigint;
        units: bigint;
        serial: string;
        originLabel: string;
        destinationLabel: string;
        exists: boolean;
      }
    ],
    "view"
  >;

  getBatch: TypedContractMethod<
    [_batchId: string],
    [MedicineTracker.BatchStructOutput],
    "view"
  >;

  getRoleAdmin: TypedContractMethod<[role: BytesLike], [string], "view">;

  getTelemetry: TypedContractMethod<
    [_batchId: string, index: BigNumberish],
    [MedicineTracker.TelemetryStructOutput],
    "view"
  >;

  getTelemetryCount: TypedContractMethod<[_batchId: string], [bigint], "view">;

  grantRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  hasRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;

  logTelemetry: TypedContractMethod<
    [
      _batchId: string,
      _latE6: BigNumberish,
      _lngE6: BigNumberish,
      _tempCp: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  provisionBatch: TypedContractMethod<
    [
      _batchId: string,
      _productName: string,
      _manufacturerLabel: string,
      _units: BigNumberish,
      _serial: string,
      _originLabel: string,
      _destinationLabel: string
    ],
    [void],
    "nonpayable"
  >;

  recordVerificationHash: TypedContractMethod<
    [_batchId: string, _payloadHash: BytesLike],
    [void],
    "nonpayable"
  >;

  registerCarrier: TypedContractMethod<
    [account: AddressLike],
    [void],
    "nonpayable"
  >;

  registerInspector: TypedContractMethod<
    [account: AddressLike],
    [void],
    "nonpayable"
  >;

  registerManufacturer: TypedContractMethod<
    [account: AddressLike],
    [void],
    "nonpayable"
  >;

  renounceRole: TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;

  revokeBatch: TypedContractMethod<
    [_batchId: string, _reason: string],
    [void],
    "nonpayable"
  >;

  revokeRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "CARRIER_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "DEFAULT_ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "INSPECTOR_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "MANUFACTURER_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "MAX_TEMP"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MIN_TEMP"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "batchTelemetry"
  ): TypedContractMethod<
    [arg0: string, arg1: BigNumberish],
    [
      [bigint, bigint, bigint, bigint, string, boolean] & {
        timestamp: bigint;
        latE6: bigint;
        lngE6: bigint;
        temperatureCp: bigint;
        signer: string;
        breached: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "batches"
  ): TypedContractMethod<
    [arg0: string],
    [
      [
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        string,
        string,
        string,
        boolean
      ] & {
        batchId: string;
        productName: string;
        manufacturer: string;
        manufacturerLabel: string;
        currentStatus: bigint;
        createdAt: bigint;
        units: bigint;
        serial: string;
        originLabel: string;
        destinationLabel: string;
        exists: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getBatch"
  ): TypedContractMethod<
    [_batchId: string],
    [MedicineTracker.BatchStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRoleAdmin"
  ): TypedContractMethod<[role: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "getTelemetry"
  ): TypedContractMethod<
    [_batchId: string, index: BigNumberish],
    [MedicineTracker.TelemetryStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTelemetryCount"
  ): TypedContractMethod<[_batchId: string], [bigint], "view">;
  getFunction(
    nameOrSignature: "grantRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "logTelemetry"
  ): TypedContractMethod<
    [
      _batchId: string,
      _latE6: BigNumberish,
      _lngE6: BigNumberish,
      _tempCp: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "provisionBatch"
  ): TypedContractMethod<
    [
      _batchId: string,
      _productName: string,
      _manufacturerLabel: string,
      _units: BigNumberish,
      _serial: string,
      _originLabel: string,
      _destinationLabel: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "recordVerificationHash"
  ): TypedContractMethod<
    [_batchId: string, _payloadHash: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "registerCarrier"
  ): TypedContractMethod<[account: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "registerInspector"
  ): TypedContractMethod<[account: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "registerManufacturer"
  ): TypedContractMethod<[account: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "renounceRole"
  ): TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeBatch"
  ): TypedContractMethod<
    [_batchId: string, _reason: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;

  getEvent(
    key: "BatchProvisioned"
  ): TypedContractEvent<
    BatchProvisionedEvent.InputTuple,
    BatchProvisionedEvent.OutputTuple,
    BatchProvisionedEvent.OutputObject
  >;
  getEvent(
    key: "BatchRevoked"
  ): TypedContractEvent<
    BatchRevokedEvent.InputTuple,
    BatchRevokedEvent.OutputTuple,
    BatchRevokedEvent.OutputObject
  >;
  getEvent(
    key: "BatchSpoiled"
  ): TypedContractEvent<
    BatchSpoiledEvent.InputTuple,
    BatchSpoiledEvent.OutputTuple,
    BatchSpoiledEvent.OutputObject
  >;
  getEvent(
    key: "BatchStatusChanged"
  ): TypedContractEvent<
    BatchStatusChangedEvent.InputTuple,
    BatchStatusChangedEvent.OutputTuple,
    BatchStatusChangedEvent.OutputObject
  >;
  getEvent(
    key: "RoleAdminChanged"
  ): TypedContractEvent<
    RoleAdminChangedEvent.InputTuple,
    RoleAdminChangedEvent.OutputTuple,
    RoleAdminChangedEvent.OutputObject
  >;
  getEvent(
    key: "RoleGranted"
  ): TypedContractEvent<
    RoleGrantedEvent.InputTuple,
    RoleGrantedEvent.OutputTuple,
    RoleGrantedEvent.OutputObject
  >;
  getEvent(
    key: "RoleRevoked"
  ): TypedContractEvent<
    RoleRevokedEvent.InputTuple,
    RoleRevokedEvent.OutputTuple,
    RoleRevokedEvent.OutputObject
  >;
  getEvent(
    key: "TelemetryLogged"
  ): TypedContractEvent<
    TelemetryLoggedEvent.InputTuple,
    TelemetryLoggedEvent.OutputTuple,
    TelemetryLoggedEvent.OutputObject
  >;
  getEvent(
    key: "VerificationRecorded"
  ): TypedContractEvent<
    VerificationRecordedEvent.InputTuple,
    VerificationRecordedEvent.OutputTuple,
    VerificationRecordedEvent.OutputObject
  >;

  filters: {
    "BatchProvisioned(string,address)": TypedContractEvent<
      BatchProvisionedEvent.InputTuple,
      BatchProvisionedEvent.OutputTuple,
      BatchProvisionedEvent.OutputObject
    >;
    BatchProvisioned: TypedContractEvent<
      BatchProvisionedEvent.InputTuple,
      BatchProvisionedEvent.OutputTuple,
      BatchProvisionedEvent.OutputObject
    >;

    "BatchRevoked(string,address,string)": TypedContractEvent<
      BatchRevokedEvent.InputTuple,
      BatchRevokedEvent.OutputTuple,
      BatchRevokedEvent.OutputObject
    >;
    BatchRevoked: TypedContractEvent<
      BatchRevokedEvent.InputTuple,
      BatchRevokedEvent.OutputTuple,
      BatchRevokedEvent.OutputObject
    >;

    "BatchSpoiled(string,address,int256)": TypedContractEvent<
      BatchSpoiledEvent.InputTuple,
      BatchSpoiledEvent.OutputTuple,
      BatchSpoiledEvent.OutputObject
    >;
    BatchSpoiled: TypedContractEvent<
      BatchSpoiledEvent.InputTuple,
      BatchSpoiledEvent.OutputTuple,
      BatchSpoiledEvent.OutputObject
    >;

    "BatchStatusChanged(string,uint8)": TypedContractEvent<
      BatchStatusChangedEvent.InputTuple,
      BatchStatusChangedEvent.OutputTuple,
      BatchStatusChangedEvent.OutputObject
    >;
    BatchStatusChanged: TypedContractEvent<
      BatchStatusChangedEvent.InputTuple,
      BatchStatusChangedEvent.OutputTuple,
      BatchStatusChangedEvent.OutputObject
    >;

    "RoleAdminChanged(bytes32,bytes32,bytes32)": TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;
    RoleAdminChanged: TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;

    "RoleGranted(bytes32,address,address)": TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;
    RoleGranted: TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;

    "RoleRevoked(bytes32,address,address)": TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
    RoleRevoked: TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;

    "TelemetryLogged(string,address,int256,bool)": TypedContractEvent<
      TelemetryLoggedEvent.InputTuple,
      TelemetryLoggedEvent.OutputTuple,
      TelemetryLoggedEvent.OutputObject
    >;
    TelemetryLogged: TypedContractEvent<
      TelemetryLoggedEvent.InputTuple,
      TelemetryLoggedEvent.OutputTuple,
      TelemetryLoggedEvent.OutputObject
    >;

    "VerificationRecorded(string,address,bytes32)": TypedContractEvent<
      VerificationRecordedEvent.InputTuple,
      VerificationRecordedEvent.OutputTuple,
      VerificationRecordedEvent.OutputObject
    >;
    VerificationRecorded: TypedContractEvent<
      VerificationRecordedEvent.InputTuple,
      VerificationRecordedEvent.OutputTuple,
      VerificationRecordedEvent.OutputObject
    >;
  };
}
